# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2psync.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rp2psync.proto\"\x07\n\x05\x45mpty\" \n\x08PeerList\x12\x14\n\x05peers\x18\x01 \x03(\x0b\x32\x05.Peer\"\"\n\x04Peer\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"5\n\x0f\x44\x61tabaseCommand\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t2\x9a\x01\n\x07P2PSync\x12$\n\x0bGetPeerList\x12\x06.Empty\x1a\t.PeerList\"\x00\x30\x01\x12.\n\x0eListenCommands\x12\x06.Empty\x1a\x10.DatabaseCommand\"\x00\x30\x01\x12\x1a\n\x07\x43onnect\x12\x05.Peer\x1a\x06.Empty\"\x00\x12\x1d\n\tHeartbeat\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_PEERLIST = DESCRIPTOR.message_types_by_name['PeerList']
_PEER = DESCRIPTOR.message_types_by_name['Peer']
_DATABASECOMMAND = DESCRIPTOR.message_types_by_name['DatabaseCommand']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'p2psync_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

PeerList = _reflection.GeneratedProtocolMessageType('PeerList', (_message.Message,), {
  'DESCRIPTOR' : _PEERLIST,
  '__module__' : 'p2psync_pb2'
  # @@protoc_insertion_point(class_scope:PeerList)
  })
_sym_db.RegisterMessage(PeerList)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
  'DESCRIPTOR' : _PEER,
  '__module__' : 'p2psync_pb2'
  # @@protoc_insertion_point(class_scope:Peer)
  })
_sym_db.RegisterMessage(Peer)

DatabaseCommand = _reflection.GeneratedProtocolMessageType('DatabaseCommand', (_message.Message,), {
  'DESCRIPTOR' : _DATABASECOMMAND,
  '__module__' : 'p2psync_pb2'
  # @@protoc_insertion_point(class_scope:DatabaseCommand)
  })
_sym_db.RegisterMessage(DatabaseCommand)

_P2PSYNC = DESCRIPTOR.services_by_name['P2PSync']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=17
  _EMPTY._serialized_end=24
  _PEERLIST._serialized_start=26
  _PEERLIST._serialized_end=58
  _PEER._serialized_start=60
  _PEER._serialized_end=94
  _DATABASECOMMAND._serialized_start=96
  _DATABASECOMMAND._serialized_end=149
  _P2PSYNC._serialized_start=152
  _P2PSYNC._serialized_end=306
# @@protoc_insertion_point(module_scope)
